filegroup(
    name = "srcs",
    srcs = glob(["**"]) + [
        "//src/main/java/org/andmed/myapp:srcs",
        "//src/test/java/org/andmed/myapp:srcs",
        "//src/main/java/org/andmed/devtools:srcs",
        "//src/test/java/org/andmed/devtools:srcs",
    ],
    visibility = ["//:__pkg__"],
)
